version: '3.8'

services:
  mongo:
    container_name: mongo
    image: mongo
    command: mongod --auth
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: 12345
      MONGO_INITDB_DATABASE: stockdb
    ports:
      - "27017:27017"
    volumes:
      - .docker/mongodb:/data/db
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
    networks:
      - stock-network

#  mongo-express:
#    container_name: mongo-express
#    image: mongo-express
#    ports:
#      - "8081:8081"
#    environment:
#      ME_CONFIG_BASICAUTH_USERNAME: admin
#      ME_CONFIG_BASICAUTH_PASSWORD: 12345
#      ME_CONFIG_MONGODB_PORT: 27017
#      ME_CONFIG_MONGODB_ADMINUSERNAME: root
#      ME_CONFIG_MONGODB_ADMINPASSWORD: 12345
#    depends_on:
#      - mongo
#    networks:
#      - stock-network

volumes:
  mongo-data:

networks:
  stock-network:
    driver: bridge