version: '3.8'

services:
  mongo:
    container_name: mongo
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 12345
    ports:
      - "27017:27017"
    volumes:
      - .docker/mongodb:/data/db
    networks:
      - stock-network

#  mongo-express:
#    container_name: mongo-express
#    image: mongo-express
#    ports:
#      - "8081:8081"
#    environment:
#      ME_CONFIG_BASICAUTH_USERNAME: admin
#      ME_CONFIG_BASICAUTH_PASSWORD: 12345
#      ME_CONFIG_MONGODB_PORT: 27017
#      ME_CONFIG_MONGODB_ADMINUSERNAME: root
#      ME_CONFIG_MONGODB_ADMINPASSWORD: 12345
#    depends_on:
#      - mongo
#    networks:
#      - stock-network

networks:
  stock-network:
    driver: bridge